import os
import csv
import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

# Carregar o modelo CLIP pré-treinado
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# Função para descrever uma imagem com base em uma lista de características
def gerar_descricao_imagem(imagem_path, lista_caracteristicas, top_k=10):
    # Abrir a imagem
    imagem = Image.open(imagem_path)

    # Processar a imagem e as características (textos)  
    entradas = processor(text=lista_caracteristicas, images=imagem, return_tensors="pt", padding=True)

    # Fazer a inferência no modelo CLIP
    saidas = model(**entradas)

    # Calcular a similaridade entre as características e a imagem
    logits_per_image = saidas.logits_per_image  # Logits da imagem
    probabilidades = logits_per_image.softmax(dim=1)  # Converter logits em probabilidades

    # Obter os índices das top_k características com maior probabilidade
    top_k_indices = probabilidades[0].topk(top_k).indices.tolist()
    
    # Retornar as top_k características e suas probabilidades
    top_k_descricoes = [(lista_caracteristicas[i], probabilidades[0][i].item()) for i in top_k_indices]
    return top_k_descricoes

# Função para processar todas as imagens em uma pasta e salvar as descrições em CSV
def processar_pasta(imagem_pasta, lista_odores_primarios, lista_odores_sub, csv_prim_path, csv_sub_path):
    with open(csv_prim_path, 'w', newline='', encoding='utf-8') as csvfile_prim, open(csv_sub_path, 'w', newline='', encoding='utf-8') as csvfile_sub:
        prim_writer = csv.writer(csvfile_prim)
        sub_writer = csv.writer(csvfile_sub)

        prim_writer.writerow(['Imagem', 'Descrição', 'Probabilidade'])
        sub_writer.writerow(['Imagem', 'Descrição', 'Probabilidade'])

        for imagem_nome in os.listdir(imagem_pasta):
            if imagem_nome.lower().endswith(('.png', '.jpg', '.jpeg')):  # Filtrar por formatos de imagem
                imagem_path = os.path.join(imagem_pasta, imagem_nome)
                
                # Gerar descrições primárias e secundárias
                descricoes_prim = gerar_descricao_imagem(imagem_path, lista_odores_primarios, top_k=10)
                descricoes_sub = gerar_descricao_imagem(imagem_path, lista_odores_sub, top_k=10)

                # Escrever descrições primárias no arquivo CSV
                for descricao, probabilidade in descricoes_prim:
                    prim_writer.writerow([imagem_nome, descricao, f"{probabilidade:.4f}"])

                # Escrever descrições secundárias no arquivo CSV
                for descricao, probabilidade in descricoes_sub:
                    sub_writer.writerow([imagem_nome, descricao, f"{probabilidade:.4f}"])

# Exemplo de uso:
lista_odores_primarios = [
    "Drinking Water Primary odor",
    "Other Primary odor",
    "Waste Water Primary odor",
    "Urban Odor Primary odor",
    "Compost Primary odor",
    "Human Perception Primary odor",
    "Wine Primary odor",
    "Perfumes Primary odor",
    "Fragrance Primary odor",
    "City Smell Primary odor",
    "Chemical/ Hydrocarbon Primary odor",
    "Ammonia Primary odor",
    "Microbial Primary odor",
    "Cooked Primary odor",
    "Rotten Primary odor",
    "Ylang Primary odor",
    "Boiled Primary odor",
    "Grains Primary odor",
    "Cloth Primary odor",
    "Raw Primary odor",
    "Vegetation Primary odor",
    "Bland Primary odor",
    "Nose Feel Primary odor",
    "Fresh Primary odor",
    "Chocolate Primary odor",
    "Plants Primary odor",
    "Balsamic Primary odor",
    "Dry fruit Primary odor",
    "Burnt Primary odor",
    "Non-vegetarian Primary odor",
    "Dairy Primary odor",
    "Salty Primary odor",
    "Zesty Primary odor",
    "Metallic Primary odor",
    "Coal tar Primary odor",
    "Ripe/ Unripe Primary odor",
    "Waxy Primary odor",
    "Bloody Primary odor",
    "Fried Primary odor",
    "Clean Primary odor",
    "Poultry Primary odor",
    "Fecal/ Sewery Primary odor",
    "Bitter Primary odor",
    "Estery Primary odor",
    "Vegetables Primary odor",
    "Sulphur/ Cabbage/ Garlic Primary odor",
    "Chlorinous Primary odor",
    "Rancid/ Putrid Primary odor",
    "Medicinal/ Alcohol Primary odor",
    "Fragrant/ Fruity Primary odor",
    "Medicinal/ Phenolic Primary odor",
    "Terpenes/ Pine/ Lemon Primary odor",
    "Bakery Primary odor",
    "Rancid Primary odor",
    "Sweet Primary odor",
    "Restaurant Primary odor",
    "Fuel/ Gas Station/ Solvent Primary odor",
    "Grassy/ Woody Primary odor",
    "Putrid/ Dead Animal Primary odor",
    "Fishy/ Rancid Primary odor",
    "Fishy/ Ammonia Primary odor",
    "Woody/ Resinous Primary odor",
    "Sickening Primary odor",
    "Popcorn Primary odor",
    "Minty Primary odor",
    "Sharp/ Pungent Primary odor",
    "Non-citrus fruity Primary odor",
    "Chlorinous/ Ozonous Primary odor",
    "Lemon Primary odor",
    "Spices Primary odor",
    "Caramel Primary odor",
    "Nutty Primary odor",
    "Herbaceous Primary odor",
    "Floral Primary odor",
    "Woody Primary odor",
    "Pungent Primary odor",
    "Microbiological Primary odor",
    "Marshy/ Septic/ Sulphurous Primary odor",
    "Fruity Primary odor",
    "Earthy Primary odor",
    "Alliaceous Primary odor",
    "Hircine Primary odor",
    "Foul Primary odor",
    "Ambrosial Primary odor",
    "Nauseating Primary odor",
    "Aromatic Primary odor",
    "Soft oriental Primary odor",
    "Fragrant Primary odor",
    "Oriental Primary odor",
    "Green Primary odor",
    "Woody oriental Primary odor",
    "Water Primary odor",
    "Citrus Primary odor",
    "Soft floral Primary odor",
    "Mossy woods Primary odor",
    "Earthy/ Musty/ Moldy Primary odor",
    "Dry woods Primary odor",
    "Tobacco smoke Primary odor",
    "Beverage Primary odor",
    "People & animals Primary odor",
    "Nature Primary odor",
    "Food Primary odor",
    "Traffic emissions Primary odor",
    "Building materials & construction Primary odor",
    "Synthetic Primary odor",
    "Solvent/ Hydrocarbon Primary odor",
    "Non-food items Primary odor",
    "Industrial odours Primary odor",
    "Waste Primary odor",
    "Cleaning materials Primary odor",
    "Characteristic Primary odor",
    "Other Primary odor",
    "Baked Primary odor",
    "Dry Primary odor",
    "Smokey Primary odor",
    "Brown Primary odor"
]

lista_odores_sub = [
    "Skunk Sub odor",
    "Gasoline Sub odor",
    "Earthy/ Potato Bin Sub odor",
    "Chemical Sub odor",
    "Sweet Solvent Sub odor",
    "Moth Balls Sub odor",
    "Glue Sub odor",
    "Ammonia Sub odor",
    "Irritating Sub odor",
    "Sharp Sub odor",
    "Metallic Sub odor",
    "Pungent Sub odor",
    "Fecal Sub odor",
    "Manure Sub odor",
    "Chloroform Sub odor",
    "Sewage Sub odor",
    "Rotten Vegetables Sub odor",
    "Burnt Rubber Sub odor",
    "Rotten Cabbage Sub odor",
    "Cabbage Sub odor",
    "Rotten Sub odor",
    "Natural Gas Sub odor",
    "Garlic Sub odor",
    "Corn Sub odor",
    "Decayed Sub odor",
    "Yeasty Sub odor",
    "Sour Milk Sub odor",
    "Fatty/ Oily Sub odor",
    "Sweaty Sub odor",
    "Pyridine Sub odor",
    "Sour Cheese Sub odor",
    "Putrid Sub odor",
    "Citrus Sub odor",
    "Soapy Sub odor",
    "Fruity Sub odor",
    "Green Sub odor",
    "Alkane Sub odor",
    "Pine Sub odor",
    "Borneol Sub odor",
    "Minty Sub odor",
    "Lemon Sub odor",
    "Terpenic Sub odor",
    "Eucalyptus Sub odor",
    "Carvone Sub odor",
    "Nail Polish Sub odor",
    "Linalool Sub odor",
    "Wet Wool Sub odor",
    "Sweet Garbage Sub odor",
    "Citral Sub odor",
    "Smokey Sub odor",
    "Biscuit Sub odor",
    "Roasted Sub odor",
    "Malty Sub odor",
    "Cookie Sub odor",
    "Toasty Sub odor",
    "Bready Sub odor",
    "Furfural Sub odor",
    "Rye bready Sub odor",
    "Marzipan Sub odor",
    "Graham cracker Sub odor",
    "Buttery Sub odor",
    "Vinegar Sub odor",
    "Sweet (Medicinal) Sub odor",
    "Bubblegum Sub odor",
    "Sugar Sub odor",
    "Vanilla Sub odor",
    "Marshmallow Sub odor",
    "Chocolate Sub odor",
    "Carbolic Sub odor",
    "Candy Sub odor",
    "Jammy Sub odor",
    "Fragrant Sub odor",
    "Warm Sub odor",
    "Cotton candy Sub odor",
    "Toffee Sub odor",
    "Benzene Sub odor",
    "Medicinal Sub odor",
    "Caramel Sub odor",
    "Beefy Sub odor",
    "Chicken Sub odor",
    "Coffee Sub odor",
    "Plastic Sub odor",
    "Fuel Sub odor",
    "Dead Animal Sub odor",
    "Alcohol Sub odor",
    "Urine Sub odor",
    "Burnt Wood Sub odor",
    "Mouldy Sub odor",
    "Vinyl Sub odor",
    "Spices Sub odor",
    "Cedarwood Sub odor",
    "Acid Sub odor",
    "Ethanol Sub odor",
    "Burnt Sub odor",
    "Foul Sub odor",
    "Peanut Butter Sub odor",
    "Almond Sub odor",
    "Solvent Sub odor",
    "Nutty Sub odor",
    "Resin Sub odor",
    "Oily Sub odor",
    "Fatty Sub odor",
    "Benzoin Sub odor",
    "Spearmint Sub odor",
    "Anisic Sub odor",
    "Menthol Sub odor",
    "Cool Sub odor",
    "Peppermint Sub odor",
    "Ketonic Sub odor",
    "Camphor Sub odor",
    "Acetoin Sub odor",
    "Sour Sub odor",
    "Tutty-Fruity Sub odor",
    "Strawberry Sub odor",
    "Banana Sub odor",
    "Pineapple Sub odor",
    "Cherry Sub odor",
    "Kerosene Sub odor",
    "Diesel Sub odor",
    "Cumin Sub odor",
    "Allspice Sub odor",
    "Pepper Sub odor",
    "Clove Sub odor",
    "Pesticide Sub odor",
    "Licorice Sub odor",
    "Cassia Sub odor",
    "Fennel Sub odor",
    "Caraway Sub odor",
    "Dill Sub odor",
    "Coriander Sub odor",
    "Nutmeg Sub odor",
    "Cinnamyl Sub odor",
    "Shoe Polish Sub odor",
    "Fenugreek Sub odor",
    "Cardamom Sub odor",
    "Eugenol Sub odor",
    "Black Pepper Sub odor",
    "Butterscotch Sub odor",
    "Molasses Sub odor",
    "Soy Sauce Sub odor",
    "Benzaldehyde Sub odor",
    "Honey Sub odor",
    "Raisin Sub odor",
    "Groundnut Sub odor",
    "Walnut Sub odor",
    "Peanut Sub odor",
    "Hazelnut Sub odor",
    "Hydrocarbon Sub odor",
    "Artichoke Sub odor",
    "Green Olive Sub odor",
    "Tobacco Sub odor",
    "Black Olive Sub odor",
    "Straw Sub odor",
    "Asparagus Sub odor",
    "Green Beans Sub odor",
    "Tarry Sub odor",
    "Tea Sub odor",
    "Bell Pepper Sub odor",
    "Freesia Sub odor",
    "Orange Blossom Sub odor",
    "Blooms Sub odor",
    "Lilac Sub odor",
    "Narcissus Sub odor",
    "Immortelle Sub odor",
    "Cleaning Fluid Sub odor",
    "Saffron Sub odor",
    "Cistus Sub odor",
    "Mahogany Sub odor",
    "Privet Sub odor",
    "Carnation Sub odor",
    "Linden flower Sub odor",
    "Fresh Cut Flower Sub odor",
    "Orchid Sub odor",
    "Bois de rose Sub odor",
    "Nitrile Sub odor",
    "Lily Sub odor",
    "Nasturtium Sub odor",
    "Jasmine Sub odor",
    "Tagette Sub odor",
    "Cyclamen Sub odor",
    "Muguet Sub odor",
    "Heliotrope Sub odor",
    "Chrysanthemum Sub odor",
    "Repellent Sub odor",
    "Magnolia Sub odor",
    "Gardenia Sub odor",
    "Peony Sub odor",
    "Camomile Sub odor",
    "Lily of the valley Sub odor",
    "Sawdust Sub odor",
    "Burnt Toast Sub odor",
    "Patchouli Sub odor",
    "Vetiver Sub odor",
    "Anaesthetic Sub odor",
    "Cedar Sub odor",
    "Sandalwood Sub odor",
    "Oak Sub odor",
    "Acetic Sub odor",
    "Fusel Sub odor",
    "Hot Sub odor",
    "Baker's Yeast Sub odor",
    "Ylang Sub odor",
    "Mousy Sub odor",
    "Horsey Sub odor",
    "Sauerkraut Sub odor",
    "Sweet Organic Chemical Sub odor",
    "Peach Sub odor",
    "Apple Sub odor",
    "Guava Sub odor",
    "Quince Sub odor",
    "Tropical Sub odor",
    "Blueberry Sub odor",
    "Papaya Sub odor",
    "Grape Sub odor",
    "Chlorinous Sub odor",
    "Prune Sub odor",
    "Blackberry Sub odor",
    "Mango Sub odor",
    "Durain Sub odor",
    "Plum Sub odor",
    "Ripe Sub odor",
    "Mercaptan Sub odor",
    "Pear Sub odor",
    "Apricot Sub odor",
    "Juicy Sub odor",
    "Unripe fruit Sub odor",
    "Cantaloupe Sub odor",
    "Passion fruit Sub odor",
    "Grapefruit Sub odor",
    "Pulpy fruit Sub odor",
    "Tangerine Sub odor",
    "Pyrazine Sub odor",
    "Blackcurrant Sub odor",
    "Melon Sub odor",
    "Fig Sub odor",
    "Pomegranate Sub odor",
    "Rotting fruit Sub odor",
    "Berry Sub odor",
    "Lychee Sub odor",
    "Dried Fruit Sub odor",
    "Artificial Fruit Sub odor",
    "Aldehydic Sub odor",
    "Kiwi Sub odor",
    "Raspberry Sub odor",
    "Dusty Sub odor",
    "Mushroom Sub odor",
    "Alliaceous Sub odor",
    "Goat Sub odor",
    "Wet Dog Sub odor",
    "Offensive Sub odor",
    "Acrid Sub odor",
    "Suffocating Sub odor",
    "Harsh Sub odor",
    "Stench Sub odor",
    "Fermented Sub odor",
    "Decomposing Sub odor",
    "Choking Sub odor",
    "Ether Sub odor",
    "Unpleasant Sub odor",
    "Obnoxious Sub odor",
    "Stinky Sub odor",
    "Garbage Sub odor",
    "Sickening Sub odor",
    "Disagreeable Sub odor",
    "Repulsive Sub odor",
    "Dead Sub odor",
    "Musk Sub odor",
    "Disgusting Sub odor",
    "Sulphurous Sub odor",
    "Lavender Sub odor",
    "Amber Sub odor",
    "Incense Sub odor",
    "Oriental Sub odor",
    "Carbide Sub odor",
    "Violet Leaves Sub odor",
    "Galbanum Sub odor",
    "Aquatic Sub odor",
    "Water Sub odor",
    "Marine Sub odor",
    "Wet Air Sub odor",
    "Thiamine Sub odor",
    "Lactonic Sub odor",
    "Bergamot Sub odor",
    "Mandarin Sub odor",
    "Powdery Sub odor",
    "Oak Moss Sub odor",
    "Acetone Sub odor",
    "Cigar Sub odor",
    "Cigarette Sub odor",
    "Marijuana Sub odor",
    "Scotch Sub odor",
    "Varnish Sub odor",
    "Absinthe Sub odor",
    "Root beer Sub odor",
    "Maraschino Sub odor",
    "Whiskey Sub odor",
    "Cognac Sub odor",
    "Tequila Sub odor",
    "Beer Sub odor",
    "Rummy Sub odor",
    "Mimosa Sub odor",
    "Winey Sub odor",
    "Disinfectant Sub odor",
    "Vinous Sub odor",
    "Brandy Sub odor",
    "Animal Sub odor",
    "Flatulence Sub odor",
    "Clam Sub odor",
    "Catty Sub odor",
    "Body Odour Sub odor",
    "Petroleum Sub odor",
    "Foxy Sub odor",
    "Civet Sub odor",
    "Castoreum Sub odor",
    "Blossom Sub odor",
    "Tree Sub odor",
    "Sea Sub odor",
    "Waterway Sub odor",
    "Plant Sub odor",
    "Fresh Air Sub odor",
    "Restaurant Sub odor",
    "Café Sub odor",
    "Market Sub odor",
    "Grease Sub odor",
    "Taco Sub odor",
    "Phenolic Sub odor",
    "Cocoa Sub odor",
    "Meaty Sub odor",
    "Kimchi Sub odor",
    "Vegetable Sub odor",
    "Food Sub odor",
    "Street Vendor Sub odor",
    "Fast Food Sub odor",
    "Bus Sub odor",
    "Train Sub odor",
    "Street Cleaning Machine Sub odor",
    "Woody Sub odor",
    "Car Sub odor",
    "Tram Sub odor",
    "Subway Sub odor",
    "Lorry Sub odor",
    "Construction Site Sub odor",
    "Tarmac Sub odor",
    "Drain Sub odor",
    "Stone Sub odor",
    "Cardboard Sub odor",
    "Acrylic Sub odor",
    "Scented Product Sub odor",
    "Air Freshener Sub odor",
    "Pharmaceuticals Sub odor",
    "Laundered cloth Sub odor",
    "Coal tar Sub odor",
    "New mown hay Sub odor",
    "Clothes Sub odor",
    "Leather Sub odor",
    "Coal Sub odor",
    "Abbatoir Sub odor",
    "Hairdresser Sub odor",
    "Dry Cleaning Sub odor",
    "Damascone Sub odor",
    "Grassy(Green, Sharp)' Sub odor",
    "Brewery Sub odor",
    "Industrial Unit Sub odor",
    "Factory Sub odor",
    "Chemical Plant Sub odor",
    "Vomit Sub odor",
    "Public Toilet Sub odor",
    "Dirt Sub odor",
    "Grassy Sub odor",
    "Waste Plant Sub odor",
    "Litter Sub odor",
    "Bleach Sub odor",
    "Limonene Sub odor",
    "Characteristic Sub odor",
    "Dried Grass Sub odor",
    "Penetrating Sub odor",
    "Agreeable Sub odor",
    "Natural Sub odor",
    "Humus Sub odor",
    "Refreshing Sub odor",
    "Fleshy Sub odor",
    "Pleasant Sub odor",
    "Diffusive Sub odor",
    "Paper Sub odor",
    "Mild Sub odor",
    "Sweet Tobacco Sub odor",
    "Strong Sub odor",
    "Gassy Sub odor",
    "Powerful Sub odor",
    "Distinctive Sub odor",
    "Baked Sub odor",
    "Baked potato Sub odor",
    "Dry Sub odor",
    "Smokey sausage Sub odor",
    "Brown Sub odor",
    "Hay Sub odor",
    "Brown sugar Sub odor",
    "Algae Sub odor",
    "Fungal Sub odor",
    "Mildew Sub odor",
    "Cooked Sub odor",
    "Cooked potato Sub odor",
    "Deep fried Sub odor",
    "Grassy (Fresh, Sweet)' Sub odor",
    "Yoghurt Sub odor",
    "Boiled Sub odor",
    "Barley Sub odor",
    "Toasted grain Sub odor",
    "Cereal Sub odor",
    "Grain Sub odor",
    "Fresh Cut Grass Sub odor",
    "Linen Sub odor",
    "Raw Sub odor",
    "Raw potato Sub odor",
    "Agarwood Sub odor",
    "Pollen Sub odor",
    "Guaiacwood Sub odor",
    "Old wood Sub odor",
    "Foliage Sub odor",
    "Weed Sub odor",
    "Aquarium Sub odor",
    "Leafy Sub odor",
    "Coniferous Sub odor",
    "Seedy Sub odor",
    "Hyacinth Sub odor",
    "Cider Sub odor",
    "Root Sub odor",
    "Hawthorn Sub odor",
    "Plowed Sub odor",
    "Forest Sub odor",
    "Rotten Fish Sub odor",
    "Cortex Sub odor",
    "Valerian root Sub odor",
    "Labdanum Sub odor",
    "Cone-like Sub odor",
    "Bland Sub odor",
    "Fresh Sub odor",
    "Fishy Sub odor",
    "Dark chocolate Sub odor",
    "Clary sage Sub odor",
    "Petitgrain Sub odor",
    "Acacia Sub odor",
    "Juniper Sub odor",
    "Spruce Sub odor",
    "Chicory Sub odor",
    "Orris Sub odor",
    "Paint Sub odor",
    "Rancid Sub odor",
    "Filbert Sub odor",
    "Sarsaparilla Sub odor",
    "Verbena Sub odor",
    "Cananga Sub odor",
    "Opoponax Sub odor",
    "Davana Sub odor",
    "Rue Sub odor",
    "Truffle Sub odor",
    "Angelica Sub odor",
    "Myrrh Sub odor",
    "Costus Sub odor",
    "Allium Sub odor",
    "Maple Sub odor",
    "Storax Sub odor",
    "Citronella Sub odor",
    "Palmarosa Sub odor",
    "Sassafrass Sub odor",
    "Capers Sub odor",
    "Ozone Sub odor",
    "Origanum Sub odor",
    "Fir needle Sub odor",
    "Sage Sub odor",
    "Turpentine Sub odor",
    "Buchu Sub odor",
    "Neroli Sub odor",
    "Cypress Sub odor",
    "Reseda Sub odor",
    "Ambrette Sub odor",
    "Marjoram Sub odor",
    "Creeky Sub odor",
    "Tonka Sub odor",
    "Balsamic Sub odor",
    "Pistachio Sub odor",
    "Pork Sub odor",
    "Bacon Sub odor",
    "Turkey Sub odor",
    "Mutton Sub odor",
    "Lard Sub odor",
    "Scallion Sub odor",
    "Ham Sub odor",
    "Salmon Sub odor",
    "Oyster Sub odor",
    "Tallow Sub odor",
    "Shrimp Sub odor",
    "Lamb Sub odor",
    "Sausage Sub odor",
    "Brothy Sub odor",
    "Buttermilk Sub odor",
    "Onion Sub odor",
    "Parmesan cheese Sub odor",
    "Limburger cheese Sub odor",
    "Creamy Sub odor",
    "Roquefort cheese Sub odor",
    "Milky Sub odor",
    "Dairy Sub odor",
    "Cheese Sub odor",
    "Salty Sub odor",
    "Savory Sub odor",
    "Decaying Vegetation Sub odor",
    "Zesty Sub odor",
    "Quinoline Sub odor",
    "Unripe Sub odor",
    "Waxy Sub odor",
    "Bloody Sub odor",
    "Swampy Sub odor",
    "Fried Sub odor",
    "Fried potato Sub odor",
    "Clean Sub odor",
    "Eggs Sub odor",
    "Poultry Sub odor",
    "Bitter Sub odor",
    "Estery Sub odor",
    "Chervil Sub odor",
    "Pea Sub odor",
    "Septic Sub odor",
    "Ginger Sub odor",
    "Turnip Sub odor",
    "Cauliflower Sub odor",
    "Cucumber Sub odor",
    "Thyme Sub odor",
    "Lettuce Sub odor",
    "Cilantro Sub odor",
    "Radish Sub odor",
    "Rubbery Sub odor",
    "Rotten Egg Sub odor",
    "Leek Sub odor",
    "Potato Sub odor",
    "Basil Sub odor",
    "Horseradish Sub odor",
    "Wasabi Sub odor",
    "Celery Sub odor",
    "Parsley Sub odor",
    "Marshy Sub odor",
    "Tomato Sub odor",
    "Carrot Sub odor",
    "Lovage Sub odor",
    "Rhubarb Sub odor",
    "Brocolli Sub odor",
    "Chilli Sub odor",
    "Pumpkin Sub odor",
    "Bean Sub odor",
    "Rose Sub odor",
    "Jackfruit Sub odor",
    "Watercress Sub odor",
    "Aromatic Sub odor",
    "Orange Sub odor",
    "Herbal Sub odor",
    "Floral Sub odor",
    "Sweet Sub odor",
    "Cologne Sub odor",
    "Perfume Sub odor",
    "Astringent Sub odor",
    "Light Sub odor",
    "Geranium Sub odor",
    "Violet Sub odor",
    "Cut Grass Sub odor",
    "Earthy Sub odor",
    "Musty Sub odor",
    "Moldy Sub odor",
    "Earthy/ Musty Sub odor",
    "Musty/Moldy Sub odor",
    "Muddy Sub odor"
]

# Exemplo de uso:
imagem_pasta = r"C:\Users\João Pedro\Documents\imagens"
csv_prim_path = 'descricoes_primarias.csv'
csv_sub_path = 'descricoes_sub.csv'

processar_pasta(imagem_pasta, lista_odores_primarios, lista_odores_sub, csv_prim_path, csv_sub_path)

print("Processamento concluído.")